version: '3.5'
services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1379
      POSTGRES_DB: ecuatourism
    volumes: 
      - ./api/database/database.sql:/docker-entrypoint-initdb.d/database.sql

  ecuatourism:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1379
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ecuatourism