version: '3.5'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./api/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: 1379
      POSTGRES_DB: ecuatourism
    ports:
      - 5432:5432
  ecuatourism:
     image: ecuatourism:latest
volumes:
  db_data: