version: 2.1

jobs:
  docker-tests:
    docker:
      - image: red98/ecuatourism
    steps:
      - checkout
      - run:
          name: "Tests in Docker container"
          command: docker run -t -v `pwd`:/app/test red98/ecuatourism

workflows:
  ci-testing:
    jobs:
      - docker-tests
