version: 2.1

jobs:
  docker-tests:
    docker:
      - image: red98/ecuatourism
      auth:
      - username: ${{ secrets.DOCKER_USERNAME }}
      - password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - checkout
      - run:
          name: "Tests in Docker container"
          command: docker version

workflows:
  ci-testing:
    jobs:
      - docker-tests
