name: Tests

on:
  push:
    paths:
      - ".github/workflows/*"
      - "docker-compose.yml"
      - "Dockerfile"

jobs:
  lanzar_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lanzar Tests
        run:
          docker version